# nixpacks.toml - Simplified version for deployment with reduced dependencies
# Use this configuration if the main nixpacks.toml fails due to complex dependencies

[variables]
# Force Python 3.11 to avoid distutils issues in Python 3.12
NIXPACKS_PYTHON_VERSION = "3.11"
# Ensure pip is updated and use legacy resolver for compatibility
PIP_DEFAULT_TIMEOUT = "120"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
# Minimal system packages for basic Python web application
pkgs = [
    "gcc", 
    "cmake",
    "pkg-config",
    "git",
    "build-essential",
    "python3.11-venv"
]

[phases.install]
# Use simplified requirements to avoid complex dependency build issues
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir --timeout=300 -r requirements-simple.txt"
]

[start]
cmd = "python slack_webhook_server.py"