# nixpacks.toml

[phases.setup]
# Add a comprehensive set of system packages required for building complex 
# Python dependencies with C++ and Fortran backends, like faiss-cpu.
pkgs = [
    "gcc", 
    "gfortran",
    "cmake",
    "pkg-config",
    "liblapack",
    "libomp"
]
