# nixpacks.toml

[variables]
# Force Python 3.11 to avoid distutils issues in Python 3.12
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
# Add a comprehensive set of system packages required for building complex 
# Python dependencies with C++ and Fortran backends, like faiss-cpu.
pkgs = [
    "gcc", 
    "gfortran",
    "cmake",
    "pkg-config",
    "liblapack",
    "libomp"
]

[phases.install]
# Ensure setuptools is available at build time for distutils compatibility
cmds = ["pip install setuptools>=65.0.0"]
