# nixpacks.toml

[variables]
# Force Python 3.11 to avoid distutils issues in Python 3.12
NIXPACKS_PYTHON_VERSION = "3.11"
# Ensure pip is updated and use legacy resolver for compatibility
PIP_DEFAULT_TIMEOUT = "120"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
# Use python311 which includes pip by default
nixPkgs = ["python311", "gcc"]

[phases.install]
# Create virtual environment and install dependencies
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --timeout=300 -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python slack_webhook_server.py"
