# nixpacks.toml

[phases.setup]
# Add a comprehensive set of system packages required for building complex 
# Python dependencies with C++ and Fortran backends, like faiss-cpu.
pkgs = [
    "gcc", 
    "gfortran",
    "cmake",
    "pkg-config",
    "liblapack",
    "libomp",
    "python311"
]

[variables]
# Force Python 3.11 to avoid distutils issues in Python 3.12
PYTHON_VERSION = "3.11"
