# nixpacks.toml

[variables]
# Force Python 3.11 to avoid distutils issues in Python 3.12
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
# Basic system packages for Python dependencies
pkgs = ["gcc"]
